#!/usr/bin/Rscript

## ./knit [epub|github|html|pdf|docx] to generate different types of output

library(knitr)
library(methods) 
## use markdown as the output format: R code in ```r and ``` 
render_markdown()

## Formatting for printed numbers
knit_hooks$set(inline = function(x) {
  if(is.numeric(x) && x > 0.001)
   I(prettyNum(round(x,2), big.mark=","))
  else
    I(x)
})

## global chunk options: default uses high quality Cairo PNG device
pdf.options(pointsize = 8)  # smaller pointsize for recording plots
opts_chunk$set(cache=TRUE, fig.path='figure/', 
               dev='png', cache.path = 'cache-local/', 
               par=TRUE)

## xtable html format for github/html output.  
## otherwise this should be ignored (defaults to 'latex') for pdf output
options(xtable.type = 'html')

## Global options 
opts_chunk$set(warning=FALSE, message=FALSE, comment=NA, tidy=FALSE)

## verbose compile
opts_knit$set(progress = TRUE, verbose = TRUE)


## Select graphics appropriate to output format
## Note that different outputs will also use different caches
local({
  fmt = commandArgs(TRUE)
  if (length(fmt) == 0L) fmt = 'github'
  if (fmt %in% c('github', 'html')) {
    # upload to flickr when output is for github or html
    opts_knit$set(upload.fun = socialR::flickr.url)
    opts_chunk$set(cache.path = 'cache-upload/', 
                   fig.width=16, fig.height=6)

  } else if (fmt == 'epub') {

  } else if (fmt %in% c('odt', 'docx', 'doc')) {
    options(xtable.type = 'html')
    # xtable shouldn't print comments 
    options(xtable.print.comment=FALSE)
    # Journal probably wants eps formatted graphics.  
    opts_chunk$set(dev = 'postscript', fig.width=8, fig.height=3, 
                   cache.path = 'cache-doc/')
    # try splitting the tables out with special options?
    options(knitr.include=TRUE)
    options(knitr.split=TRUE)
    # We'll want plots to be external only with word docs
    knit_hooks$set(plot = function(x, options) "") 

  } else if (fmt %in% c('tex','pdf')) {
    options(xtable.print.comment=FALSE)
    options(xtable.type = 'latex', table.placement="ht")
    opts_chunk$set(cache.path = 'cache-pdf/')
    # use pdf graphics for PDF output
    opts_chunk$set(dev = 'pdf', fig.width=8, fig.height=3)
    pdf.options(pointsize = 8)  # smaller pointsize for recording plots
 }
    knit("treebase.Rmd")
    knit("appendix.Rmd")
})



